---
name: CI
on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
jobs:
  ci:
    runs-on: "${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.13
      - id: cache-settings
        run: 'echo "::set-output name=dir::$(npm config get cache)"'
      - uses: actions/cache@v3
        with:
          key: "${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}"
          path: "${{ steps.cache-settings.outputs.dir }}"
          restore-keys: "${{ runner.os }}-"
      - run: "npm ci"
      - run: "npm test"
      - run: "npm pack"
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
