---
name: QL
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    - cron: '26 19 * * 3'
jobs:
  ql:
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: github/codeql-action/init@v1
        with:
          languages: "${{ matrix.language }}"
      - uses: github/codeql-action/autobuild@v1
      - uses: github/codeql-action/analyze@v1
    strategy:
      fail-fast: false
      matrix:
        language:
          - javascript
